import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cupboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <h1>
          <strong>Q</strong>
        </h1>
        <Content />
      </main>
    </>
  );
}

function Content() {
  const { data: sessionData } = useSession();

  return (
    <div>
      <h1>Hello</h1>
    </div>
  );
}
